builds:
  - targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
universal_binaries:
  - replace: true
changelog:
  use: github
release:
brews:
  - tap:
      owner: leancodepl
      name: poe2arb
    folder: Formula
    homepage: "https://github.com/leancodepl/poe2arb"
    description: "POEditor JSON to Flutter ARB converter."
