# This file was generated by GoReleaser. DO NOT EDIT.
cask "poe2arb" do
  name "poe2arb"
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"
  version "2.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poe2arb"

  on_macos do
    url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_darwin_all.tar.gz"
    sha256 "4d594ebaa768b0dfe316d08310e6394dedf7989caefc93157086e9d764fc2cc8"
  end

  on_linux do
    on_intel do
      url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_linux_amd64.tar.gz"
      sha256 "9cab7cb98610dfea287d78e056dec1b27f89fefbcc25830ae7ba4fdc5c957261"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poe2arb"]
    end
    generate_completions_from_executable(bin/"poe2arb", "completion")
  end

  # No zap stanza required
end
