# This file was generated by GoReleaser. DO NOT EDIT.
cask "poe2arb" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/poe2arb"]
    end
  end

  version "2.6.0"

  on_macos do
    sha256 "c2d7dd031feb0e2aff90cd555263e50c0c211d993f975a5e7abccbcc90f0a104"
    url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_intel do
      sha256 "d0d8ab49402bbe64c45393b6204467aaf062a895034f18b6cac53a7f9dea1d64"
      url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poe2arb"
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poe2arb"

  # No zap stanza required
end
