# This file was generated by GoReleaser. DO NOT EDIT.
cask "poe2arb" do
  name "poe2arb"
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"
  version "2.5.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poe2arb"

  on_macos do
    url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_darwin_all.tar.gz"
    sha256 "128a040de7a950ab7bb001e9d3306f915e84089d6addcd2a241cba9bf8b456ce"
  end

  on_linux do
    on_intel do
      url "https://github.com/leancodepl/poe2arb/releases/download/v#{version}/poe2arb_#{version}_linux_amd64.tar.gz"
      sha256 "76dff9eab77f5fd2a02ded6d9e5c9bdb7bcb2c5ac5383c2b19fa09a3fb65e5b4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poe2arb"]
    end
  end

  # No zap stanza required
end
