# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poe2arb < Formula
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"
  version "0.1.1"

  on_macos do
    url "https://github.com/leancodepl/poe2arb/releases/download/v0.1.1/poe2arb_0.1.1_darwin_all.tar.gz"
    sha256 "963e3cb6849de21a41c4b24b787caf6ea2ae8deafbf967c8d53bc188e9d2c166"

    def install
      bin.install "poe2arb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leancodepl/poe2arb/releases/download/v0.1.1/poe2arb_0.1.1_linux_amd64.tar.gz"
      sha256 "3d7dc93c84c1d6a5b93fd5b99e71fc75b264b166e97a7cfc010dc4a678b5c00f"

      def install
        bin.install "poe2arb"
      end
    end
  end
end
