# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poe2arb < Formula
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"
  version "2.1.0"

  on_macos do
    url "https://github.com/leancodepl/poe2arb/releases/download/v2.1.0/poe2arb_2.1.0_darwin_all.tar.gz"
    sha256 "85352987a4e73950e6c2a9b59ffab60ddd859c79734fc48b2b491528516933fd"

    def install
      bin.install "poe2arb"
      generate_completions_from_executable(bin/"poe2arb", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leancodepl/poe2arb/releases/download/v2.1.0/poe2arb_2.1.0_linux_amd64.tar.gz"
      sha256 "8ea4dfb841d3f5b248a850cc22ec80d8c0d245d1d4117b14acb6dc01baea7848"

      def install
        bin.install "poe2arb"
        generate_completions_from_executable(bin/"poe2arb", "completion")
      end
    end
  end
end
