# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poe2arb < Formula
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/poe2arb"
  version "0.5.0"

  on_macos do
    url "https://github.com/leancodepl/poe2arb/releases/download/v0.5.0/poe2arb_0.5.0_darwin_all.tar.gz"
    sha256 "e303313452e9f8c2eff92035ffc8d3943dc0720bf987aff25b5beb2edb8f5f1d"

    def install
      bin.install "poe2arb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leancodepl/poe2arb/releases/download/v0.5.0/poe2arb_0.5.0_linux_amd64.tar.gz"
      sha256 "841a2f1eb459d143f3db26040fb156d3229c58ffd04eb80b58ed27e546290c24"

      def install
        bin.install "poe2arb"
      end
    end
  end
end
