name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Go 1.19

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify code formatting
        run: |
          go install mvdan.cc/gofumpt@v0.4
          test -z $(gofumpt -l .)

      - name: Run linter
        if: always()
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.3
          staticcheck ./...

      - name: Run tests with coverage
        if: always()
        run: go test -cover ./...

  smoke-test:
    name: Smoke test with Flutter ${{ matrix.flutter_version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter_version: ['3.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binary
        run: go install .

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter_version }}'

      - name: Run smoke test
        run: |
          cd smoke_test
          ./test.sh

      - name: Upload lib/l10n/ artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-l10n-dir
          path: |
            smoke_test/lib/l10n/
            !smoke_test/lib/l10n/.gitignore